### ISSUE TITLE
mouseup event is not handled at browser borders

### ISSUE THREAD

**Issue by ymatrokhin** [michaelmalonenz/aurelia-dragula#23]
Hi!

I have a problem with dropping element, which is moved outside document body, for example to browser toolbar or page scroll area,

Steps to reproduce:
1. start dragging element
2. move mouse pointer to the most top of browser window
3. release mouse button

result: nothing happened, element is still bound to pointer 
expected: element is released, "drop" or "cancel" event is called

I've noticed, that "mouseup" event listener is attached to document.body in Dragula.prototype._events method. But in bevacqua Dragula implementation event are attached to document.documentElement; 
(please look at https://github.com/bevacqua/dragula/blob/master/dragula.js, function events)

Will you fix this issue, please?

**Comment by michaelmalonenz** [comment]
Huh, never understood what `documentElement` did and my reading about it suggested it was an out-dated way of saying `document.body` which is why I changed it.  Live and learn, I guess.  Anyway, it's fixed for me, now.

**Comment by ymatrokhin** [comment]
Thanks, now it works.
