### ISSUE TITLE
Flicker on drop

### ISSUE THREAD

**Issue by Askadar** [michaelmalonenz/aurelia-dragula#24]
Example case here: https://github.com/Askadar/planner, left pane with todos, most related stuff in src/todos.
The problem - on dropping `<li>` element somewhere in list there's noticeble flicker. It looks like dragula does the reorder and shows new correct list, then aurelia catchs up and re-renders old list, then gets updated one from dragula and re-renders it again, final correct one. 
I suppose this have something to do with either aurelia and dragula not communicating properly or me screwing something up installing and configurating stuff (it's my first app in aurelia basically, so I still get to know stuff).

**Comment by michaelmalonenz** [comment]
You've more or less described the situation exactly - fixing this issue requires re-architecting the whole library :(

I will have a look later on when I get home from work if I remember (in around 8 hours), there might be strategties to reduce the flicker - it's certainly not been an issue for me.  But yeah, the library does the drag, figures out where to drop it, then calls `cancel` and then hands over to the client code to do the logical re-order and then waits for Aurelia to render the results.

If you are doing the physical re-order, then it will be happening twice and there might be a flicker.  That's the main thing, I'll be looking for.

**Comment by michaelmalonenz** [comment]
My docs clearly aren't very clear as several people have made this mistake, now.  You should delete this line:
https://github.com/Askadar/planner/blob/master/src/todos/todos.js#L12

It's unnecessary, and I think it might be getting involved and doing too much.  I will look into re-doing my docs at some stage, and potentially re-architecting the library at some other stage.  Maybe.  (though it wouldn't be a dragula port after that!)

**Comment by michaelmalonenz** [comment]
Turns out this was pretty straight forward to fix.  It's done now, I just needed sufficient motivation.
