### ISSUE TITLE
Drag Multiple Items

### ISSUE THREAD

**Issue by cottrellio** [michaelmalonenz/aurelia-dragula#28]
Any chance there is support for dragging multiple items? I looked through your docs, but I don't see anything.

To give a little context, I have a table with `<tr>` items that are draggable. I have a tr repeater that is `record in data` and am toggling `record.isSelected` with CMD + click fn. So I was hoping once I've selected the records I want to drag, I would click one of the selected and drag and ALL the selected records would move.

Anyways, great work. From what I've seen playing around with your plugin, it's really easy to use. Thanks!

**Comment by michaelmalonenz** [comment]
Sorry, but no.  Nearly the whole library would need to be re-written to accommodate that.  There is definite knowledge of the current item as being a single thing.

Also, much of the credit goes to @bevacqua , as this is merely an aurelia port of Dragula.
