### ISSUE TITLE
Can't load aurelia.use.plugin('aurelia-dragula') with new aurelia-webpack-plugin

### ISSUE THREAD

**Issue by nashwaan** [michaelmalonenz/aurelia-dragula#33]
**I'm submitting a bug report**

**Current behavior**
Using `aurelia.use.plugin('aurelia-dragula');` in `main.js` - `export function configure(aurelia) {}` will not work with the new `aurelia-webpack-plugin` v2 (currently 2.0.0-rc.2). 

**Expected behavior** Be able to load `aurelia-dragula` plugin without issues under `aurelia-webpack-plugin` v2.

**Minimal reproduction of the problem with instructions**
Please download minimal Aurelia + Webpack setup from [here](https://github.com/nathanchase/super-minimal-aurelia). Then do the following simple steps.

```npm install --save aurelia-dragula```

```js
import {PLATFORM} from 'aurelia-framework';
export function configure(aurelia) {
  aurelia.use
     .standardConfiguration()
     .plugin(PLATFORM.moduleName('aurelia-dragula')) // <--- wrapping in PLATFORM.moduleName()
     .developmentLogging();
  aurelia.start().then(() => aurelia.setRoot(PLATFORM.moduleName('app')));
}
```

Under new `aurelia-webpack-plugin` it is required to wrap `aurelia-dragula` by `PLATFORM.moduleName()`. See more info about [`PLATFORM.moduleName()`](https://github.com/jods4/aurelia-webpack-build/wiki/Managing-dependencies).

However, the browser gives this error:
```Uncaught (in promise) Error: Unable to find module with ID: aurelia-dragula/dragula-and-drop```

I think internally, `aurelia-dragula` should load all sub-modules using `PLATFORM.moduleName()`

**Reason for this issue**
As `aurelia-webpack-plugin` is upgrading to v2 (currently 2.0.0-rc.2), `aurelia-dragula` will fail to load on webpack setups.

**My environment:** Windows, VS Code, Webpack, Webpack Dev Server

**aurelia-dragula version:** 1.3.3

_____

Note: I tried to use the following as a [temporary solution](https://github.com/ceolter/ag-grid-aurelia/issues/10#issuecomment-289856472) in `webpack.config.js`:
```js
const AureliaWebpackPlugin = require('aurelia-webpack-plugin');
...
// under .plugins: []  section
new AureliaWebpackPlugin.ModuleDependenciesPlugin({
    'aurelia-dragula': ['./dragula-and-drop'] // temp HACK
}),
```
But this also raised an error in the browser:
```
Uncaught (in promise) Error: Failed loading required CSS file: aurelia-dragula/dragula.css
```
@jods4 any idea how to get `dragula.css` loaded by `ModuleDependenciesPlugin`?

**Comment by jods4** [comment]
`ModuleDependenciesPlugin` doesn't load anything, it only adds dependencies (ensures bundling).
Something has to load the CSS (typically `<require>` or `import`).

`Failed loading required CSS file: aurelia-dragula/dragula.css` usually indicates a file that was loaded by Aurelia (`<require>`) but included a `style-loader`.

And that's the tricky part with CSS, really. **Your** build has to setup the Webpack loaders properly, although how the file is actually imported is dependent on the library :(

**Comment by michaelmalonenz** [comment]
so at the moment, the css is loaded via `@inlineView('<template><require from="./dragula.css"></require></template>')`  The `dragula-and-drop` only has a view such that it can pull in the css.  This is the way that makes sense for jspm-based apps (which is what I was targeting when I wrote the plugin initially).  

If there is a way that I can import the css in a way that helps out the webpack users, too, then I'm quite happy to do so, however, I don't know very much about webpack at all, and haven't worked on any Aurelia apps for almost a year now, which seems to be an eternity in JS.  

If you put up a PR, I will likely merge it, but other than that, it is highly unlikely I will spend any time trying to update this plugin for WebPack.

**Comment by jods4** [comment]
Quick note here: unfortunately Aurelia Webpack plugin doesn't analyze `@inlineView` yet, so to bundle the `dragula.css` file you'll need a `PLATFORM.moduleName('./dragula.css')` next to it, at least for now.

As for importing CSS in a cross-tools way I don't think there's a great solution now. Something to be looked at for sure.

In the meantime, `<require>` is probably the way, but it should be clear for Webpack consumers that this piece of CSS _should not go through `style-loader`_.

I have a sample where I automatically choose `style-loader` or not based on the file the imports the stylesheet (`.js` vs `.html`) but it's unfortunately broken in this scenario since -- by way of `inlineView` -- this is a `<require>` from inside a `.js` :(

**Comment by michaelmalonenz** [comment]
would it work if I used a regular html view file, just to `<require>` the css?

**Comment by jods4** [comment]
It would work better for Webpack users that use the code snippet at the end of this page:
https://github.com/aurelia/webpack-plugin/wiki/CSS-doesn't-load

Because the issuer would be `.html`, `style-loader` would not be used.

HTML files are analyzed by Webpack plugin and that would not require the `PLATFORM.moduleName` either (although I intend to fix that at some point and support `inlineView`).

That being said, I am not sure what the impact on other build systems would be? Would the HTML file be automatically picked up and properly bundled by JSPM or RequireJS for example? 😭

**Comment by michaelmalonenz** [comment]
It would work just fine for jspm, don't know about requirejs.  I'll do this when I have a bit more time to test - like the weekend, perhaps. Let me see when I get the time to do it

**Comment by nashwaan** [comment]
I did the following changes in `src/` folder to make this package works for the new aurelia-webpack-plugin:

In `src/index.js`:
Changed this line:
```js
  config.globalResources(['./dragula-and-drop']);
```
To this to avoid `AureliaWebpackPlugin.ModuleDependenciesPlugin()` hack:
```js
  import {PLATFORM} from 'aurelia-framework'; // you can optionally add this line at the top

  config.globalResources([PLATFORM.moduleName('./dragula-and-drop')]);
```

Also,
In `src/dragula-and-drop.js`, made following changes as denoted by (1), (2), (3), and (4):
```js
import {customElement, bindable, noView} from 'aurelia-templating'; // (1) 'noView' instead of 'inlineView'
import {bindingMode} from 'aurelia-binding';
import {inject} from 'aurelia-dependency-injection';

import {Options, GLOBAL_OPTIONS} from './options';
import {Dragula} from './dragula';
import './dragula.css'; // (2) importing css directly here

@bindable({ name: 'moves', defaultBindingMode: bindingMode.oneTime })
@bindable({ name: 'accepts', defaultBindingMode: bindingMode.oneTime })
@bindable({ name: 'invalid', defaultBindingMode: bindingMode.oneTime })
@bindable({ name: 'containers', defaultBindingMode: bindingMode.oneTime })
@bindable({ name: 'isContainer', attribute: 'is-container', defaultBindingMode: bindingMode.oneTime })
@bindable({ name: 'copy', defaultBindingMode: bindingMode.oneTime })
@bindable({ name: 'copySortSource', defaultBindingMode: bindingMode.oneTime })
@bindable({ name: 'revertOnSpill', attribute: 'revert-on-spill', defaultBindingMode: bindingMode.oneTime, defaultValue: true })
@bindable({ name: 'removeOnSpill', attribute: 'remove-on-spill', defaultBindingMode: bindingMode.oneTime })
@bindable({ name: 'direction', defaultBindingMode: bindingMode.oneTime })
@bindable({ name: 'ignoreInputTextSelection', attribute: 'ingore-input-text-selection', defaultBindingMode: bindingMode.oneTime })
@bindable({ name: 'mirrorContainer', attribute: 'mirror-container', defaultBindingMode: bindingMode.oneTime })
@bindable({ name: 'targetClass', attribute: 'target-class', defaultBindingMode: bindingMode.oneTime, defaultValue: 'drop-target' })
@bindable({ name: 'sourceClass', attribute: 'source-class', defaultBindingMode: bindingMode.oneTime, defaultValue: 'drag-source' })
@bindable({ name: 'dragFn', attribute: 'drag-fn', defaultBindingMode: bindingMode.oneTime })
@bindable({ name: 'dropFn', attribute: 'drop-fn', defaultBindingMode: bindingMode.oneTime })
@bindable({ name: 'dragEndFn', attribute: 'drag-end-fn', defaultBindingMode: bindingMode.oneTime })
@bindable({ name: 'clonedFn', attribute: 'cloned-fn', defaultBindingMode: bindingMode.oneTime })
@bindable({ name: 'overFn', attribute: 'over-fn', defaultBindingMode: bindingMode.oneTime })
@bindable({ name: 'outFn', attribute: 'out-fn', defaultBindingMode: bindingMode.oneTime })
@bindable({ name: 'shadowFn', attribute: 'shadow-fn', defaultBindingMode: bindingMode.oneTime })
@customElement('dragula-and-drop')
//@inlineView('<template><require from="./dragula.css"></require></template>') // (3) can't be parsed by new aurelia-webpack-plugin
@noView() // (4) have to tell aurelia no 'dragula-and-drop.html' counterpart for this component
@inject(GLOBAL_OPTIONS)
export class DragulaAndDrop {
```

I build your project via `gulp build` and now everything works. I assume these changes will work for `jspm` users.

**Comment by nashwaan** [comment]
Pull request https://github.com/michaelmalonenz/aurelia-dragula/pull/34 is submitted for the above suggested changes.

If this is accepted, then I hope the updated version of this packages is published to npm sometime soon.
Thanks.

**Comment by michaelmalonenz** [comment]
I've released this as part of v1.4.0 - thanks to you both @nashwaan and @jods4 for your help on this issue!

**Comment by nashwaan** [comment]
Thanks for accepting the changes. I tried to use v1.4.0 but it did not work!
I got this error from the browser:
`Uncaught (in promise) Error: Unable to find module with ID: aurelia-dragula/dragula-and-drop.html`

Sorry @michaelmalonenz but this is my mistake. I missed one important thing:
```js
@useView('./dragula-and-drop.html')
```
should be
```js
@useView(PLATFORM.moduleName('./dragula-and-drop.html'))
```
Because `PLATFORM.moduleName` should also be used in `@useView()` see [this](https://github.com/jods4/aurelia-webpack-build/wiki/Managing-dependencies) for more info.

I can submit another pull request, but I prefer that you do it (to make commit history less noisy).

**Comment by nashwaan** [comment]
Also, I couldn't find `dragula-and-drop.html` file in any folder inside of `dist\` folder. Was it skipped from the build?

**Comment by michaelmalonenz** [comment]
@nashwaan I've updated it a bit more - thanks for pointing out the html thing, my build step didn't have any rules for html, so skipped it!  I've also removed the `moduleName` in the call to `useView` because I couldn't get that working with the jspm example program.  If you could test v1.4.3 as it stands, that would be much appreciated.

Thanks again for your input!

**Comment by nashwaan** [comment]
It works!
But I don't understand why it worked. 
`dragula-and-drop.js` has `@useView('./dragula-and-drop.html')`. No `PLATFORM.moduleName()` is used and I am not using `ModuleDependenciesPlugin()` in `webpack.config.js` and yet this thing worked this time. Strange!!!
