### ISSUE TITLE
Dracula will throw error when you drop an element if you are using dragulaModel and the element is not in the target

### ISSUE THREAD

**Issue by jack1006** [michaelmalonenz/aurelia-dragula#36]
I have an element that I want to drag. When I drop, a drop event is fired in dragula-provider.js. If I am not using DraculaModel, the method returns which is fine. If I am using dragulaModel, the following line is executed:

Target.removeChild(dropElm); // element must be remove for ngFor to apply correctly

This causes problems as it assumes that the element being dropped is already in the targets model which it may not be. Imagine you want to drag between components or between bags. 

Error: DOMException: failed to execute 'removeChild' no 'Node'. The node to be removed is not a child of this node

**Comment by michaelmalonenz** [comment]
That particular line of code doesn't exist in this repository.  Are you perhaps mistaking this, an `Aurelia` plugin, for the Angular bridge?
