### ISSUE TITLE
Not all files get bundled using aurelia-bundler

### ISSUE THREAD

**Issue by timfish** [michaelmalonenz/aurelia-dragula#38]
Thanks for this plugin, it significantly simplifies using dragula with aurelia!

One problem I've noticed is that when using JSPM/SystemJS and the aurelia bundler, the `jspm_packages/npm/aurelia-dragula@1.4.4/dragula-and-drop.js` file is not getting bundled.

Have you seen this before or is it something to with my setup?

**Comment by michaelmalonenz** [comment]
please see the [example app](https://github.com/michaelmalonenz/aurelia-dragula-example/blob/master/build/bundles.js#L34-L36) for how I solved this issue.
