### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by J4ck4l0pe** [michaelmalonenz/aurelia-dragula#4]
in:
`<dragula-and-drop drop.call="itemDropped(item, target, source, sibling)"></dragula-and-drop>`

`drop.call` should be `drop-fn.call`

`<dragula-and-drop drop-fn.call="itemDropped(item, target, source, sibling)"></dragula-and-drop>`

**Comment by michaelmalonenz** [comment]
Thanks - you're quite right!
