### ISSUE TITLE
Using the Dragula object in the js code

### ISSUE THREAD

**Issue by Lambik** [michaelmalonenz/aurelia-dragula#41]
I apologize if this comes across the internet as being aggressive, or disrespectful of the large amount of code you've produced for free, but I'm feeling frustrated after trying for a few hours to fully use the potential of the aurelia-dragula project, in combination with webpack and typescript.

I would like to specify a custom function for containers, which is supported by the dragula object. However, I cannot seem to get it to work in my typescript code. You mention somewhere that it's incorrect to use both the html component and the js code at the same time (which is currently my code), but the error I'm getting from typescript implies that 'Dragula is a type, not instantiable', not something related to using the component. I am confused as to how I should get this object, as the documentation is not clear, nor is the example project, on this matter.

**Comment by michaelmalonenz** [comment]
view:
```
<dragula-and-drop is-container.call="myIsContainerFunct(item)"></dragula-and-drop>
```

viemodel:
```
export class ViewModel {
  myIsContainer(item) {
    return item.classList.includes('container')
  }
}
```

**Comment by Lambik** [comment]
Cool, thanks for the info!
