### ISSUE TITLE
drop.fn called on drag

### ISSUE THREAD

**Issue by J4ck4l0pe** [michaelmalonenz/aurelia-dragula#5]
Don't know if it's supposed to work this way, but the drop-fn is also called on drag, not only on drop which, for me is a real hazzle to work around.

**Comment by michaelmalonenz** [comment]
Nope - shouldn't be being called.  I'll see what I can do.  If, in the meantime you see what's wrong, feel free to create a pull request :)

**Comment by J4ck4l0pe** [comment]
i suppose the drop event could be linked to a mouseUp to prevent it from happening anywhere else?

**Comment by michaelmalonenz** [comment]
It is linked to a mouse up, but because of the slightly weird way in which things are done and the sheer amount of things being done, my best guess at this stage is that there is a race between the mousemove event and the mousedown handler completing.
