### ISSUE TITLE
How to set container specific options?

### ISSUE THREAD

**Issue by Piees** [michaelmalonenz/aurelia-dragula#52]
On beforehand I want to say that I have asked this question on stackoverflow and was asked to try here.

I want to be able to set revertOnSpill and removeOnSpill on only specific elements and in  dragula(JS?) you're able to do something like this to create settings based on specific elements:

`dragula([document.getElementById(left), document.getElementById(right)], {
  copy: function (el, source) {
    return source === document.getElementById(left)
  },
  accepts: function (el, target) {
    return target !== document.getElementById(left)
  }
});`

According to the documentation I don't see a way to configure this as it isn't a function with element parameter.

Stackoverflow: https://stackoverflow.com/questions/54573862/how-to-set-container-specific-options-in-aurelia-dragula

**Comment by michaelmalonenz** [comment]
I've answered on StackOverflow with what I believe will work.  Everything that's possible in `dragula.js` should be possible in `aurelia-dragula` and with interface compatibility - I did a straight fork and port.  The custom element is designed to be a wrapper to make it easier to use.

**Comment by michaelmalonenz** [comment]
Thanks for that - there was a bug. The copy function was being called by the dragula engine, as opposed to the dragula-and-drop element. So, it wasn't being called how aurelia binding expects, and therefore passing the params incorrectly. I've released a fix in v2.0.3

**Comment by Piees** [comment]
This seems to perfectly solve my issue. Thanks!
