### ISSUE TITLE
TypeScript typings cause compile errors

### ISSUE THREAD

**Issue by josundt** [michaelmalonenz/aurelia-dragula#57]
A few functions declared in the TypeScript typings file cause compile errors since return type is missing.

Should be a quite quick fix.

**Comment by michaelmalonenz** [comment]
I don't use / know typescript, so it's not a quick fix for me. Feel free to help out with a PR, though!

**Comment by josundt** [comment]
I actually attempted to now, but I can't even run `gulp build` after checking out the code and running `npm install` + `jspm install`.

Seems like gulp 3.x has an issue with current node LTS version (12.x): https://stackoverflow.com/questions/55921442/how-to-fix-referenceerror-primordials-is-not-defined-in-node
 
I think it is time to update the devDependencies and the affected build tasks before anyone can contribute.

**Comment by michaelmalonenz** [comment]
Stop telling me that I need to do something for you. As an open source project owner, I have already given you thousands of dollars of my time _for free_ 

I do not owe you anything, you do not get to come to my corner of the web and tell me that the thing you're not paying for is not good enough.

You can raise issues to attempt to help me see an issue, but you may not act so entitled about it.
