### ISSUE TITLE
Using function to determine whether or not to copy does not work

### ISSUE THREAD

**Issue by gerfen** [michaelmalonenz/aurelia-dragula#7]
Thanks for creating this Aurelia plugin!

When configuring the plugin to use a function to determine whether or not to create a copy during a drag and drop operation, the plugin never calls the assigned function and behaves as if options.copy is set the the default of false.
```
aurelia.use
    .standardConfiguration()
        .developmentLogging()
      .plugin('aurelia-dragula', (options) => {
          //options.copy = true;
          options.copy = (el, source) => (source === $('#my-source'));
          options.accepts = (el, target) => (target !== $('#my-source'));
      })
```
Looking at your source, it appears that copy is being treated only as a Boolean:

```
  DragulaAndDrop.prototype._setupOptions = function _setupOptions() {
      var result = {
        containers: this._getOption('containers'),
       ** copy: this._getOption('copy'),**
        copySortSource: this._getOption('copySortSource'),
        revertOnSpill: this._getOption('revertOnSpill'),
        removeOnSpill: this._getOption('removeOnSpill'),
        direction: this._getOption('direction'),
        ignoreInputTextSelection: this._getOption('ignoreInputTextSelection'),
        mirrorContainer: this._getOption('mirrorContainer')
      };
      return result;
    };
```

By default, Dragula does not allow sorting when copy is set to true. Being able to use a function allows for sorting of copied items in the drop target container.

An example of setting up the copy option looks like this (taken from the Dragula [documentation](http://bevacqua.github.io/dragula/))

```
dragula([document.getElementById(left), document.getElementById(right)], {
  copy: function (el, source) {
    return source === document.getElementById(left)
  },
  accepts: function (el, target) {
    return target !== document.getElementById(left)
  }
});
```

**Comment by michaelmalonenz** [comment]
That was kinda intentional on my behalf, trying to simplify my code (and the usage of the Custom Element) and I would see if anyone wanted the function feature.  Evidently you do, so I'll look into making it work again.  Thanks for your feedback!

**Comment by gerfen** [comment]
@michaelmalonenz Thanks so much!  Please let me know if there is anything I can do to assist.

**Comment by michaelmalonenz** [comment]
Pull Requests are always welcome :wink:

**Comment by gerfen** [comment]
I tried to take a pass at an implementation this afternoon before posting an issue but wasn't successful.  I modeled the copy function after your accepts implementation and changed

```
this.copy = true;
```
to 
```
this.copy = Options.never;
```
In the constructor for Options.

If you can give me some better guidance, I'd be more than happy to give it another try.  :smile:

**Comment by michaelmalonenz** [comment]
Ok, I have just tried to reproduce it and have failed - when I set up a function as `copy` in the global options like so:  
```javascript
import 'bootstrap';

export function configure(aurelia) {
  aurelia.use
    .standardConfiguration()
    .developmentLogging()
    .plugin('aurelia-dragula', options => {
      options.copy = (el, source) => {
        console.log('Calling global Copy');
        return false;
      };
    })
    .plugin('aurelia-animator-css')
    .globalResources('nbspvalueconverter');

  aurelia.start().then(() => aurelia.setRoot());
}
```

I get the logging and I can hit a breakpoint inside the function and inspect the elements.

Though I've just had a thought.  Sorry I didn't see it earlier - `(source === $('#my-source'));` will *always* return false because jQuery's `$('selector')` returns a jQuery object, not a plain HTMLElement, as is returned here.

If you do set the function like:
```javascript
import 'bootstrap';

export function configure(aurelia) {
  aurelia.use
    .standardConfiguration()
    .developmentLogging()
    .plugin('aurelia-dragula', options => {
      options.copy = (el, source) => source.id === '#my-source';
      options.accepts = (el, target) => target.id !== '#my-source';
    })
    .plugin('aurelia-animator-css')
    .globalResources('nbspvalueconverter');

  aurelia.start().then(() => aurelia.setRoot());
}
```

Then you should find it functions as you expect.

**Comment by gerfen** [comment]
Thanks Michael.  I managed to get things working late last night.   My Aurelia configuration code was contrived so I didn't actually test with that code but you are of course correct WRT to the JQuery selector.    I got the current unit tests passing again with my changes.  Would you like me to send you a pull request?

**Comment by michaelmalonenz** [comment]
I don't know what changes you're referring to?  The requested functionality already works... However, if there is something you want in the library, then of course you're welcome to open a PR.  But if it's just changing the default of the `copy` option to `Options.never` then I'd like to avoid changing the API for the sake of it.

**Comment by gerfen** [comment]
Thanks Michael.  You are correct, the code works as-is.  I'll close this issue.
