### ISSUE TITLE
Setting options for individual instance

### ISSUE THREAD

**Issue by doeck** [michaelmalonenz/aurelia-dragula#8]
First of all, thank you for this great plugin. 

My problem is, I can't get the options to work locally.
Probably I'm just missing something or doing something wrong because setting the options globally works fine.

What I have is this:
It's a simple sortable list, the first item should be fixed in it's position, only the other items should be able to be moved.

sandbox.html:
```html
<template>
        <dragula-and-drop drop-fn.call="itemDropped(item, target, source, sibling)"></dragula-and-drop>
        <ul class="list-group drag-source drop-target" id="list">
            <li repeat.for="i of items" class="list-group-item" fixed.bind="$first">
                <span class="${ $first ? 'fa fa-bullseye' : 'ao-draggable fa fa-arrows'}"></span> ${i}
            </li>
        </ul>
</template>
```
sandbox.js:
```javascript
import {Dragula, Options} from 'aurelia-dragula';

export class Sandbox {
 
    items = ["Anton", "Berti", "Conny", "Det", "Edi", "Fritzchen"];
    
    bind() {
        let options = new Options();
        options.invalid = (el, handle) => {
            return el.fixed;
        }
        
        let dragula = new Dragula(options);
    }

    itemDropped(item, target, source, sibling) {
        // do something
    }
}
```

Could you have a look at this, please? My invalid-function seems to work, it looks like it's just not connected to the drag-and-drop-list.
What is the best step of the aurelia lifecycle to set the options? (I tried some other one, none worked.)

**Comment by michaelmalonenz** [comment]
It's because you have two instances of the dragula library.  The `<dragula-and-drop>` maintains its own version of the `Dragula` object, so you have correctly set the options for the instance that isn't being involved in the `drop` event (because the `Dragula` object doesn't have defaults which are as friendly).

So, the fix is as follows:   
sandbox.html   
```html
<template>
        <dragula-and-drop drop-fn.call="itemDropped(item, target, source, sibling)" invalid.call="isInvalid(item, handle)"></dragula-and-drop>
        <ul class="list-group drag-source drop-target" id="list">
            <li repeat.for="i of items" class="list-group-item" fixed.bind="$first">
                <span class="${ $first ? 'fa fa-bullseye' : 'ao-draggable fa fa-arrows'}"></span> ${i}
            </li>
        </ul>
</template>
```
sandbox.js   
```javascript
export class Sandbox {

    items = ["Anton", "Berti", "Conny", "Det", "Edi", "Fritzchen"];

    isInvalid(item, handle) {
         return item.fixed;
    }

    itemDropped(item, target, source, sibling) {
        // do something
    }
}
```

Except that this still won't work - `item` is an instance of [HtmlElement](https://developer.mozilla.org/en/docs/Web/API/HTMLElement) so `fixed` is undefined, and I don't know what your intentions are there.

**Comment by michaelmalonenz** [comment]
Sorry, just re-read your question and I have a more complete solution for you.  You probably want to use the `moves` function, not `invalid`.

sandbox.html   
```html
<template>
        <dragula-and-drop drop-fn.call="itemDropped(item, target, source, sibling)" moves.call="canDrag(item)"></dragula-and-drop>
        <ul class="list-group drag-source drop-target" id="list">
            <li repeat.for="i of items" class="list-group-item ${$first ? 'js-fixed-position' : ''}" >
                <span class="${ $first ? 'fa fa-bullseye' : 'ao-draggable fa fa-arrows'}"></span> ${i}
            </li>
        </ul>
</template>
```

sandbox.js   
```javascript
export class Sandbox {

    items = ["Anton", "Berti", "Conny", "Det", "Edi", "Fritzchen"];

    canDrag(item) {
         return item.classList.contains('js-fixed-position');
    }

    itemDropped(item, target, source, sibling) {
        // do something
    }
}
```

You can add the other arguments to the `moves` function as required, but you don't need to bind all of them if you don't use them.

**Comment by doeck** [comment]
Thanks for answering so fast!

Both the solutions you provided work / do what I expect them to do.
`invalid.call="isInvalid(item, handle)"`was exactly the thing I was missing.

I'll see it this or the moves function will suit my more complicated real life scenario better.

Thanks for your help!
